### ISSUE TITLE
AttributeError: 'Promise' object has no attribute 'exited'

### ISSUE THREAD

**Issue by shvechikov** [pyinvoke/invoke#742]
I'm trying to run a trivial example of asynchronous execution:
`run("sleep 1", asynchronous=True)`

I'm getting the following traceback:
```
[ins] In [2]: run("sleep 1", asynchronous=True)
Out[2]: ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/usr/local/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    400                         if cls is not object \
    401                                 and callable(cls.__dict__.get('__repr__')):
--> 402                             return _repr_pprint(obj, self, cycle)
    403
    404             return _default_pprint(obj, self, cycle)

/usr/local/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    695     """A pprint that just redirects to the normal repr function."""
    696     # Find newlines and replace them with p.break_()
--> 697     output = repr(obj)
    698     for idx,output_line in enumerate(output.splitlines()):
    699         if idx:

/usr/local/lib/python3.7/site-packages/invoke/runners.py in __repr__(self)
   1466         # represents
   1467         template = "<Result cmd={!r} exited={}>"
-> 1468         return template.format(self.command, self.exited)
   1469
   1470     @property

AttributeError: 'Promise' object has no attribute 'exited'
```

I'm able to reproduce it on both MacOS 10.15.4 + Python 3.7.5 and Ubuntu 16.04.4 + Python 3.7.1

**Comment by shvechikov** [comment]
After a quick debug session I see that execution itself works fine. The issue relates to an API inconsistency:
- Promise is a Result subclass
- but it doesn't call super().__init__() so self.exited is never initialized
- base __repr__ method relies on self.exited

@bitprophet I would able to propose a fix for the issue but I don't have enough context on your plans about this API. I would drop direct inheritance here and replace it with wrapped properties (for attributes like .exited) with an explicit check that Promise is already resolved. What do you think?

**Comment by razvanioan** [comment]
No news on this yet ? It still cannot be used asynchronously ...

**Comment by elspacedoge** [comment]
I am having this issue as well...




> No news on this yet ? It still cannot be used asynchronously ...

You should be able to use asynchonously, you just wont be able to display/print the returned Promise...

**Comment by aunsbjerg** [comment]
Just ran into this problem myself. My use case is that I have an application which consists of multiple processes that must be started individually. I want to be able to It looks something like this:

```python
@task
def run(ctx):
    processes = []

    def _run_service(service):
        process = ctx.run(
            f"./{service}",
            asynchronous=True,
            out_stream=sys.stdout,
            err_stream=sys.stderr,
            pty=True,
        )

        if not process.ok:
            sys.exit(process.return_code)

        processes.append(process)

    for service in services:
        _run_service(service, log_level)

    for process in processes:
        process.join()
```

The problem is as has been mentioned before in this thread, that `Promise` inherits from `Result` but does not call the init function of `Result` so `exited` is never initialized and the code cannot run.

**Comment by Hermanoid** [comment]
Putting the workaround in clearer terms for the populace:

The failing reference to self.exited only exists under `Result.__repr__`, which is only called when an interactive python session asks for a nice representation of the Promise object. If you avoid asking for it, everything works.

For example, this breaks:
```
connection.run("sleep 1", asynchronous=True)
```

But this works just fine:
```
result = connection.run("sleep 1", asynchronous=True)
print(result.join())
```
